
lxml 
pyowm
wikipedia
youtube-dl
bs4
discord
flask
pafy
PyNaCl
youtube-search-python
bottle 
google
pyjokes
lyricsgenius
pylyrics
lyrics-extractor
emoji-translate
google-images-download
spacy
google-images-search
simplejson
pytz
music-recommender
oauth
discord-ext-ipc
profanity 
covid19-data
syllables
pyiku 
pyverse
textcaptcha 
praw

Quart

asyncpraw
spotipy
discord-pretty-help
replit
config
psutil
pymongo
dnspython
ratelimit
flask-cors
flask-limiter
discord-py-slash-command
wavelink
discord-ext-menus

